Vishal/Vishal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('piks.urls')),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Vishal/piks/urls.py
from django.urls import path
from .views import user_list, user_create, user_edit, user_delete


urlpatterns = [
  path('', user_list, name='user_list'),
     path('create/', user_create, name='user_create'),
     path('edit/<int:pk>/', user_edit, name='user_edit'),
     path('delete/<int:pk>/', user_delete, name='user_delete'),
  
]

Vishal/piks/models.py
from django.db import models

# Create your models here.

class User(models.Model):
   usr_heading = models.CharField(max_length=100)
   usr_description = models.CharField(max_length=100)
   usr_code_box = models.CharField(max_length=1000)
   usr_image = models.CharField(max_length=100)

   def __str__(self):
       return self.usr_heading

Vishal/piks/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
   class Meta:
       model = User
       fields = ['usr_heading', 'usr_description', 'usr_code_box', 'usr_image']

Vishal/piks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import User
from .forms import UserForm

def user_list(request):
   users = User.objects.all()
   return render(request, 'users/user_list.html', {'users': users})

def user_create(request):
   if request.method == 'POST':
       form = UserForm(request.POST, request.FILES)
       if form.is_valid():
           form.save()
           return redirect('user_list')
   else:
       form = UserForm()
   return render(request, 'users/user_form.html', {'form': form})

def user_edit(request, pk):
   user = get_object_or_404(User, pk=pk)
   if request.method == 'POST':
       form = UserForm(request.POST, request.FILES, instance=user)
       if form.is_valid():
           form.save()
           return redirect('user_list')
   else:
       form = UserForm(instance=user)
   return render(request, 'users/user_form.html', {'form': form})

def user_delete(request, pk):
   user = get_object_or_404(User, pk=pk)
   if request.method == 'POST':
       user.delete()
       return redirect('user_list')
   return render(request, 'users/user_confirm_delete.html', {'user': user})
# Create your views here.

def home(request):
  pt = "piks/html/home.html"
  dt = {
    "nm":"Vishal Gaud",
  }
  return render(request, pt, dt)

Vishal/piks/templates/piks/html/home.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
    <link rel="stylesheet" href="{% static 'piks/css/style.css' %}" title="main" type="text/css" />
    
  </head>
  <body>
    <h1>This is Home Page {{nm}}</h1>
    <h2><a href="{% url 'home' %}">Home Page</a></h2>
    <h2><a href="admin/">Admin Page</a></h2>
    <div class="info" id="info"></div>
    <div class="outer clickable">
      
    </div>
    
    <script src="{% static 'piks/js/script.js' %}" type="text/javascript" charset="utf-8"></script>
  </body>
</html>

Vishal/piks/templates/users/user_confirm_delete.html
<!DOCTYPE html>
{% load static %}
     <html>
     <head>
       
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
         <title>Delete User</title>
         <link rel="stylesheet" href="{% static 'piks/css/user.css' %}" title="main" type="text/css" />
     </head>
     <body>
         <h1>Delete User</h1>
         <p>Are you sure you want to delete "{{ user.usr_name }}"?</p>
         <form method="post">
             {% csrf_token %}
             <button type="submit">Confirm</button>
         </form>
         <a href="{% url 'user_list' %}">Cancel</a>
         <script src="{% static 'piks/js/script.js' %}" type="text/javascript" charset="utf-8"></script>
     </body>
     </html>

Vishal/piks/templates/users/user_form.html
<!DOCTYPE html>
{% load static %}
     <html>
     <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
         <title>User Form</title>
         <link rel="stylesheet" href="{% static 'piks/css/user.css' %}" title="main" type="text/css" />
     </head>
     <body>
         <h1>{% if form.instance.pk %}Edit User{% else %}Add User{% endif %}</h1>
         
         <a href="{% url 'user_list' %}">Cancel</a>
    <div class="user-form">
      <form action="" method="post" accept-charset="utf-8" enctype="multipart/form-data">
        {% csrf_token %}
        <ul>
          <li>
            <label for="id_usr_image">Topic </label>
            <input type="text" name="usr_image" id="id_usr_image value="" placeholder="Topic"/>
          </li>
          <li>
            <label for="id_usr_heading">Heading </label>
            <input type="text" name="usr_heading" id="id_usr_heading" value="" placeholder="Heading"/>
          </li>
          <li>
            <label for="id_usr_description">Descriptions </label>
            <input type="text" name="usr_description" id="id_usr_description" value="" placeholder="Descriptions"/>
          </li>
          <li>
            <label for="id_usr_code_box">Code Box </label>
            <textarea name="usr_code_box" id="id_usr_code_box" rows="8" cols="40" placeholder="Code Box"></textarea>
          </li>
          
          <li>
            <button type="submit">Save Data</button>
          </li>
        </ul>
      </form>
    </div>
         <script src="{% static 'piks/js/script.js' %}" type="text/javascript" charset="utf-8"></script>
     </body>
     </html>

Vishal/piks/templates/users/user_list.html
<!DOCTYPE html>
{% load static %}
     <html>
     <head>
       
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
         <title>User List</title>
         <link rel="stylesheet" href="{% static 'piks/css/style.css' %}" title="main" type="text/css" />
         <link rel="stylesheet" href="{% static 'piks/css/user.css' %}" title="main" type="text/css" />
     </head>
     <body>
         <h1 class="web_page"><a href="admin/">Admin Panel</a></a>
         <h1>Your Record</h1>
         <h3 class="web_page"><a href="{% url 'user_create' %}">Add User</a></a>

      <div class="container">
        {% for user in users %}
        <div class="subbox">
          <div class="box">
            <h1>{{ user.usr_heading }}</h1>
            <p>{{ user.usr_description }}</p>
            <pre>
              {{ user.usr_code_box }}
            </pre>
          </div>
          <div class="imgs">
            <p>{{ user.usr_image }}</p>
            
          </div>
          <div class="links">
            <div class="btn btn1">
              <a href="{% url 'user_edit' user.pk %}">Edit</a>
            </div>
            <div class="btn btn2">
              <a href="{% url 'user_delete' user.pk %}">Delete</a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
        <script src="{% static 'piks/js/script.js' %}" type="text/javascript" charset="utf-8"></script>
     </body>
     </html>